const fs = require('fs');
const vm = require('vm');

console.log('================================================================');
console.log('KIỂM TRA TOÀN BỘ SỐ SERIAL / MÃ NỘI BỘ TRONG HỆ THỐNG');
console.log('================================================================');

// 1. Đọc dữ liệu từ src_demo/05_mock_data.js
const mockDataContent = fs.readFileSync('src_demo/05_mock_data.js', 'utf8');

// Tạo sandbox để lấy SERIAL_DB
const sandbox = {
  window: {},
  localStorage: {
    getItem: () => null,
    setItem: () => {}
  }
};
vm.createContext(sandbox);

// Bỏ các thẻ script html nếu có
const cleanCode = mockDataContent.replace(/<\/?script[^>]*>/gi, '');
try {
  vm.runInContext(cleanCode, sandbox);
} catch (e) {
  console.log('Lỗi chạy mock_data:', e.message);
}

const serialDb = sandbox.window.SERIAL_DB || sandbox.SERIAL_DB || [];
console.log(`Tổng số thiết bị trong SERIAL_DB: ${serialDb.length}`);

// 2. Phân tích các mã Serial & Mã nội bộ
const serialMap = new Map();
const internalIdMap = new Map();

const duplicateSerials = [];
const duplicateInternalIds = [];
const malformedInternalIds = [];
const emptyInternalIds = [];
const internalAssetIdPattern = /^TA-\d{6}-\d{6}$/; // Chuẩn: TA-YYMMDD-XXXXXX

let internalAutoGeneratedCount = 0;
let mfgSerialCount = 0;

serialDb.forEach((item, index) => {
  const serial = String(item.serial || '').trim();
  const internalId = String(item.internalId || item.maNoiBo || '').trim();
  const model = item.model || '';
  const status = item.status || '';

  // Kiểm tra trùng Serial hãng
  if (serial) {
    const upperSerial = serial.toUpperCase();
    if (serialMap.has(upperSerial)) {
      duplicateSerials.push({
        serial,
        model,
        firstIndex: serialMap.get(upperSerial),
        duplicateIndex: index
      });
    } else {
      serialMap.set(upperSerial, index);
    }
  } else {
    duplicateSerials.push({ serial: '(RỖNG)', model, index });
  }

  // Kiểm tra Serial hãng có phải là mã tự sinh TA- không
  if (serial.startsWith('TA-')) {
    internalAutoGeneratedCount++;
  } else {
    mfgSerialCount++;
  }

  // Kiểm tra Mã nội bộ (Internal ID)
  if (internalId) {
    const upperInternalId = internalId.toUpperCase();
    if (internalIdMap.has(upperInternalId)) {
      duplicateInternalIds.push({
        internalId,
        serial,
        model,
        firstIndex: internalIdMap.get(upperInternalId),
        duplicateIndex: index
      });
    } else {
      internalIdMap.set(upperInternalId, index);
    }

    // Kiểm tra định dạng chuẩn
    if (!internalAssetIdPattern.test(internalId)) {
      malformedInternalIds.push({
        internalId,
        serial,
        model,
        index
      });
    }
  } else {
    emptyInternalIds.push({
      serial,
      model,
      index
    });
  }
});

console.log('\n--- KẾT QUẢ THỐNG KÊ ---');
console.log(`- Serial hãng (quét/nhập): ${mfgSerialCount}`);
console.log(`- Serial mã nội bộ tự sinh (bắt đầu bằng TA-): ${internalAutoGeneratedCount}`);
console.log(`- Tổng số mã nội bộ (internalId) ghi nhận: ${internalIdMap.size}`);

const taSerials = serialDb.filter(s => s.serial && s.serial.startsWith('TA-'));
console.log('\nChi tiết các thiết bị có Serial hãng bắt đầu bằng TA- (Mã tự sinh gán làm Serial):');
taSerials.forEach(s => {
  console.log(`  Serial: ${s.serial} | Mã nội bộ: ${s.internalId} | Model: ${s.model} | Trạng thái: ${s.status}`);
});

console.log('\n--- KẾT QUẢ KIỂM TRA TRÙNG LẶP & ĐỊNH DẠNG ---');
console.log(`1. Trùng Serial thiết bị: ${duplicateSerials.length}`);
if (duplicateSerials.length > 0) {
  console.log('   Chi tiết trùng serial:', duplicateSerials);
} else {
  console.log('   ✓ Tuyệt đối không trùng bất kỳ Serial nào!');
}

console.log(`2. Trùng Mã nội bộ (internalId): ${duplicateInternalIds.length}`);
if (duplicateInternalIds.length > 0) {
  console.log('   Chi tiết trùng internalId:', duplicateInternalIds);
} else {
  console.log('   ✓ Tuyệt đối không trùng bất kỳ mã nội bộ nào!');
}

console.log(`3. Mã nội bộ sai quy chuẩn định dạng (TA-YYMMDD-XXXXXX): ${malformedInternalIds.length}`);
if (malformedInternalIds.length > 0) {
  console.log('   Chi tiết mã nội bộ sai định dạng:', malformedInternalIds.slice(0, 10));
} else {
  console.log('   ✓ 100% mã nội bộ khớp đúng định dạng TA-YYMMDD-XXXXXX!');
}

console.log(`4. Thiết bị thiếu mã nội bộ (để trống internalId): ${emptyInternalIds.length}`);
if (emptyInternalIds.length > 0) {
  console.log(`   Có ${emptyInternalIds.length} thiết bị chưa có mã internalId`);
}

console.log('\n================================================================');
